# Site settings
title: Gene Ontology
email: TBD@geneontology.org
description: >
  The Gene Ontology (GO) project is a major bioinformatics initiative
  to develop a computational representation of our evolving knowledge
  of how genes encode biological functions at the molecular, cellular
  and tissue system levels.

baseurl: "/go-docs" # the subpath of your site, e.g. /blog/
url: https://kltm.github.io/go-docs # the base hostname & protocol for your site
git_address: https://github.com/kltm/go-docs
git_edit_address: https://github.com/kltm/go-docs/blob/master/docs

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: readable

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: America/Los_Angeles
defaults:

- scope:
    path: _docs
    type: docs
  values:
    sectionid: docs
    layout: docs
    seo:
      type: "WebPage"

# - scope:
#     path: _faq
#     type: docs
#   values:
#     sectionid: faq
#     layout: docs
#     seo:
#       type: "WebPage"

- scope:
    path: _posts
    type: posts
  values:
    sectionid: blog
    layout: post

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  # faq:
  #   permalink: /:collection/:path/
  #   output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
